name: Maite Uralde
favicon: null
layout_spectrum: 0.4914
typography_spectrum: 0.4509
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f37268'
    - '#1db6d5'
    - '#fcbeaa'
    - '#000000'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
